"""add language to settings

Revision ID: 96df8f3b4731
Revises: c4f0100c427c
Create Date: 2026-06-12 11:05:57.876419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96df8f3b4731'
down_revision: Union[str, None] = 'c4f0100c427c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('language', sa.String(), nullable=True))
    op.execute("UPDATE settings SET language = 'en' WHERE language IS NULL")
    op.alter_column('settings', 'language', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'language')
    # ### end Alembic commands ###
