"""add_timezone_to_settings

Revision ID: c4f0100c427c
Revises: 0ea4b2a2f545
Create Date: 2026-06-05 15:17:14.214469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4f0100c427c'
down_revision: Union[str, None] = '0ea4b2a2f545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('timezone', sa.String(), server_default='Browser Local', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'timezone')
    # ### end Alembic commands ###
