"""initial_schema

Revision ID: db382becdc57
Revises: 
Create Date: 2026-05-24 16:36:22.300948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db382becdc57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_backup', sa.DateTime(), nullable=True),
    sa.Column('disk_type', sa.String(), nullable=False),
    sa.Column('network_iface', sa.String(), nullable=True),
    sa.Column('ssh_pub_key', sa.Text(), nullable=True),
    sa.Column('efi_uuid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_hostname'), 'nodes', ['hostname'], unique=True)
    op.create_index(op.f('ix_nodes_id'), 'nodes', ['id'], unique=False)
    op.create_index(op.f('ix_nodes_ip_address'), 'nodes', ['ip_address'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('borg_ssh_port', sa.Integer(), nullable=False),
    sa.Column('borg_repo_path', sa.String(), nullable=False),
    sa.Column('keep_daily', sa.Integer(), nullable=False),
    sa.Column('keep_weekly', sa.Integer(), nullable=False),
    sa.Column('keep_monthly', sa.Integer(), nullable=False),
    sa.Column('global_exclusions', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_table('task_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('log_output', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_logs_id'), 'task_logs', ['id'], unique=False)
    op.create_table('backup_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.Integer(), nullable=False),
    sa.Column('archive_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('original_size', sa.BigInteger(), nullable=False),
    sa.Column('deduplicated_size', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('log_output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_history_archive_name'), 'backup_history', ['archive_name'], unique=True)
    op.create_index(op.f('ix_backup_history_id'), 'backup_history', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backup_history_id'), table_name='backup_history')
    op.drop_index(op.f('ix_backup_history_archive_name'), table_name='backup_history')
    op.drop_table('backup_history')
    op.drop_index(op.f('ix_task_logs_id'), table_name='task_logs')
    op.drop_table('task_logs')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_nodes_ip_address'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_hostname'), table_name='nodes')
    op.drop_table('nodes')
    # ### end Alembic commands ###
