"""add_comment_and_os_version

Revision ID: faf76df11151
Revises: 52d93226efae
Create Date: 2026-06-05 11:38:24.788846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf76df11151'
down_revision: Union[str, None] = '52d93226efae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_history', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('nodes', sa.Column('os_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'os_version')
    op.drop_column('backup_history', 'comment')
    # ### end Alembic commands ###
